version: "3.3"
services:
  redis:
    image: redis
    command: [ "redis-server", "--protected-mode", "no" ]
    ports:
      - "6379:6379"
    networks:
      - platform
  database:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'platform'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    networks:
      - platform
networks:
  platform:
    external: false
