version: "3.3"
services:
  redis:
    image: redis
    command: [ "redis-server", "--protected-mode", "no" ]
    ports:
      - "6379:6379"
    networks:
      - spring
networks:
  spring:
    external: true
