package app.gui.dialog;

import app.gui.panel.OneLineRemoveContributorPanel;
import app.util.Paged;
import app.util.Resources;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import core.entity.Article;
import core.entity.superficial.SuperficialUser;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;

public class RemoveContributorDialog extends JDialog {

    private JPanel contentPane;
    private JPanel panel;

    private Article article;

    public RemoveContributorDialog(Article article, Paged paged) {

        $$$setupUI$$$();
        setContentPane(contentPane);
        setModal(true);

        this.article = article;

        setSize(500, 700);
        setIconImage(Resources.getImageIcon("article.png").getImage());

        // call onCancel() when cross is clicked
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                dispose();
            }
        });

        // call onCancel() on ESCAPE
        contentPane.registerKeyboardAction(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                dispose();
            }
        }, KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);

        populateContributors(article, paged);


    }

    private void populateContributors(Article article, Paged paged) {
        int contributorCount = article.getContributors().size();
        ((GridLayout) panel.getLayout()).setRows(Math.max(5, contributorCount));
        for (SuperficialUser user : article.getContributors()) {
            panel.add(new OneLineRemoveContributorPanel(user, article.getId(), paged).getPanel());
        }
    }

    private void createUIComponents() {
        panel = new JPanel(new GridLayout(0, 1));
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        contentPane = new JPanel();
        contentPane.setLayout(new GridLayoutManager(1, 1, new Insets(10, 10, 10, 10), -1, -1));
        contentPane.add(panel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, 1, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }
}
