package app.gui.page;

import app.gui.panel.ProfileArticlePanel;
import app.gui.panel.ProfileInformationPanel;
import app.util.Paged;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import core.DataHandler;
import core.entity.User;
import core.util.ApiResponse;
import core.util.DataListener;

import javax.swing.*;
import java.awt.*;

public class ProfilePage {

    //TODO image save bug

    private JPanel panel;
    private JPanel InformationPanel;

    private JPanel articlePanel;
    private JPanel informationPanel;
    private JButton logoutButton;
    private JButton searchButton;

    private DataHandler dataHandler;

    ProfileInformationPanel profileInformationPanel;
    ProfileArticlePanel profileArticlePanel;

    private Paged paged;

    public ProfilePage(Paged paged) {
        this.paged = paged;
        $$$setupUI$$$();
        dataHandler = DataHandler.getDataHandler();
    }

    public void start() {
        dataHandler.getMeAsync(new DataListener<User>() {
            @Override
            public void onResult(ApiResponse<User> response) {
                profileInformationPanel.loadAndStartPanel(response.getData());
                profileArticlePanel.loadAndStartPanel(response.getData());
            }
        });
    }

    public void stop() {
        profileInformationPanel.interrupt();
    }

    public JPanel getPanel() {
        return panel;
    }

    private void createUIComponents() {

        profileInformationPanel = new ProfileInformationPanel();
        profileArticlePanel = new ProfileArticlePanel(paged);

        informationPanel = profileInformationPanel.getPanel();
        articlePanel = profileArticlePanel.getPanel();

    }


    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        panel = new JPanel();
        panel.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        panel.add(articlePanel, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        panel.add(informationPanel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }
}
